# Generated by Django 4.2.4 on 2023-09-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
    ]
