# Generated by Django 4.2.4 on 2023-09-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_telegramuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_name',
        ),
    ]
