# Generated by Django 4.2.4 on 2023-09-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rename_first_name_telegramuser_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='name_en',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='name_ru',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='name_uz',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='name_en',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='name_ru',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='name_uz',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
