# Generated by Django 4.2.4 on 2023-09-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_alter_regionmodel_name_en_alter_regionmodel_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='tgbot.categorymodel'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='tgbot.regionmodel'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='tgbot.rolemodel'),
        ),
    ]
