# Generated by Django 4.2.4 on 2023-09-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_telegramuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(blank=True, default='uz', max_length=2, null=True),
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='role',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='role',
            field=models.ManyToManyField(default=1, to='tgbot.rolemodel'),
        ),
    ]
