# Generated by Django 4.2.4 on 2023-09-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_alter_telegramuser_language_remove_telegramuser_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='role',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='tgbot.rolemodel'),
        ),
    ]
