# Generated by Django 4.2.4 on 2023-09-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_remove_telegramuser_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
