# Generated by Django 4.2.4 on 2023-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_alter_telegramuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
    ]
