# Generated by Django 4.2.4 on 2023-09-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_telegramuser_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='cat',
            new_name='category',
        ),
    ]
